version: '3'

services:
  web:  # (passenger + sidekiq)
    build: .
    environment:
      PASSENGER_APP_ENV: development
      MYSQL_HOST: db
      REDIS_URL: redis://redis:6379/1

  db:
    image: mariadb:10.4
    volumes:
      - ./docker/conf/my.local.cnf:/etc/mysql/conf.d/my.local.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      
  # redis:
  #   image: redis:5.0-32bit  # not really 32-bit, just compiled that way to reduce memory usage
